.gitignore
readme.md

rg-5: + Updated readme

---

frontend/src/bundles/common/components/progress/progress.tsx
frontend/src/bundles/common/components/progress/styles.module.scss

- Implemented the Progress component, allowing for customizable progress visualization.
- Developed a styles module specifically for the Progress component.

rg-13: Add progress component

---

frontend/src/bundles/common/enums/app-route.enum.ts
frontend/src/bundles/preview/preview.tsx
frontend/src/bundles/preview/styles.module.scss
frontend/src/index.tsx
package.json
project.config.ts

Added preview page
Example using components I made

rg-26: Add component preview

---

.gitignore
frontend/package.json
frontend/src/app/app.tsx
frontend/src/assets/img/cross.svg
frontend/src/bundles/auth/components/sign-in-form/sign-in-form.tsx
frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
frontend/src/bundles/common/components/button/button.tsx
frontend/src/bundles/common/components/components.ts
frontend/src/bundles/common/components/modal/modal.tsx
frontend/src/bundles/common/components/modal/styles.module.scss
frontend/src/bundles/common/enums/enums.ts
frontend/src/bundles/common/enums/modal/modal-variant.enum.ts
frontend/src/bundles/common/hooks/hooks.ts
frontend/src/bundles/common/hooks/use-modal/use-modal.ts
frontend/src/bundles/common/types/modal/modal-handlers.type.ts
frontend/src/bundles/common/types/modal/modal-properties.type.ts
frontend/src/bundles/common/types/modal/modal.ts
frontend/src/bundles/common/types/types.ts
package-lock.json
project.config.ts

- Added modal component
- Added use-modal hook (possibility to close on-outside-click)
- Added styles and types
I have commented on a question and kindly ask you to check it :)
P.S going to remove the comment after a review
Is it okay to leave some notes in such format - // TODO: task description?

rg-24-add-base-modal

---

frontend/package.json
frontend/src/bundles/common/components/text-editor/styles.module.scss
frontend/src/bundles/common/components/text-editor/text-editor.tsx

I have created a text editor component according to task #23. I used [react-quill](https://www.npmjs.com/package/react-quill) library.

rg-23: Add Text Editor

---

frontend/src/bundles/common/components/switch/switch.tsx

rg-19: add switch onchange

---

frontend/src/assets/img/tick.svg
frontend/src/bundles/common/components/components.ts
frontend/src/bundles/common/components/stepper/step/step.tsx
frontend/src/bundles/common/components/stepper/step/styles.module.scss
frontend/src/bundles/common/components/stepper/stepper.tsx
frontend/src/bundles/common/components/stepper/styles.module.scss
frontend/src/bundles/home/pages/home.tsx
frontend/src/bundles/home/pages/templates.tsx
package-lock.json

rg-50: Stepper

---

frontend/src/bundles/cv-editor/components/online-editor/tabs-constants.tsx
frontend/src/bundles/cv-editor/enums/languages-levels.enum.ts
frontend/src/bundles/cv-editor/enums/technical-skills.enum.ts
frontend/src/bundles/cv-editor/pages/certification/certificarion.tsx
frontend/src/bundles/cv-editor/pages/certification/certification.tsx
frontend/src/bundles/cv-editor/pages/certification/styles.module.scss
frontend/src/bundles/cv-editor/pages/contact-info/contact-info.tsx
frontend/src/bundles/cv-editor/pages/contact-info/styles.module.scss
frontend/src/bundles/cv-editor/pages/education/education.tsx
frontend/src/bundles/cv-editor/pages/education/styles.module.scss
frontend/src/bundles/cv-editor/pages/experience/experience.tsx
frontend/src/bundles/cv-editor/pages/experience/styles.module.scss
frontend/src/bundles/cv-editor/pages/languages/languages.tsx
frontend/src/bundles/cv-editor/pages/languages/styles.module.scss
frontend/src/bundles/cv-editor/pages/personal-info/personal-info.tsx
frontend/src/bundles/cv-editor/pages/personal-info/styles.module.scss
frontend/src/bundles/cv-editor/pages/technical-skills/styles.module.scss
frontend/src/bundles/cv-editor/pages/technical-skills/technical-skills.tsx
frontend/src/bundles/cv-editor/types/certification/certification.type.ts
frontend/src/bundles/cv-editor/types/contact-info/contact-info.type.ts
frontend/src/bundles/cv-editor/types/education/education.type.ts
frontend/src/bundles/cv-editor/types/languages/languages.type.ts
frontend/src/bundles/cv-editor/types/personal-info/personal-info.type.ts
frontend/src/bundles/cv-editor/types/technical-skills/technical-skills.type.ts

Added forms for resume builder.

rg-49: Resume builder forms

---

frontend/src/app/app.tsx
frontend/src/bundles/auth/pages/styles.module.scss

Removed unused items from app component and fixed full screen of auth forms.

rg-74: Clean Up Starter

---

frontend/src/bundles/profile/enums/profile.ts
frontend/src/bundles/profile/profile-api.ts
frontend/src/bundles/profile/store/actions.ts
frontend/src/bundles/profile/store/slice.ts
frontend/src/bundles/profile/types/user-profile-responce.ts
shared/src/enums/api-path.enum.ts
shared/src/enums/content-type.enum.ts

Add fix to:
1. enum ContentType  - add  FORM_DATA = "multipart/form-data"
2. import { ProfileApiPath } from 'shared/build/index' - change export in shared

rg-110: + fix after merge task 28

---

frontend/src/bundles/auth/pages/auth.tsx
frontend/src/bundles/common/enums/app-route.enum.ts
frontend/src/bundles/common/titles/titles.ts
frontend/src/bundles/preview/preview.tsx
frontend/src/index.tsx

I've replaced 'sign-in' path and tab with 'log-in'

rg-101: change tab for log in page

---

frontend/src/bundles/auth/components/sign-up-form/validation/sign-up-validation.ts
shared/src/bundles/users/enums/user-validation-message.enum.ts

1 Added validation for password in registration form (password without spaces)

rg-96: no password with spaces

---

frontend/src/bundles/preview/preview.tsx
frontend/src/bundles/preview/styles.module.scss

I've added button examples into preview page

rg-112: add buttons to preview

---

frontend/src/bundles/preview/preview.tsx
frontend/src/bundles/preview/styles.module.scss

rg-117: + Added footer, header and dropdown components to preview

---

frontend/src/bundles/landing-page/landing-page.tsx
frontend/src/bundles/landing-page/styles.module.scss

rg-126: Add Header To Landing Page

---

frontend/src/bundles/auth/pages/auth.tsx

Add error message when a user attempts to register an account with an email address that already exists in the system

rg-93: registration page br 3

---

backend/src/bundles/stripe-events/repositories/subscription-plan.repository.ts
backend/src/bundles/stripe-events/stripe-events.service.ts

rg-143: Refactor Stripe Events Service

---

backend/src/bundles/payment/payment.service.ts
backend/src/bundles/payment/payment.ts
backend/src/bundles/users/user.model.ts
backend/src/bundles/users/user.repository.ts
backend/src/bundles/users/user.service.ts
backend/src/common/database/enums/database-column-name.enum.ts
backend/src/migrations/20240210124346_create_tables.ts
backend/src/migrations/20240306135909_add_user_stripe_key.ts

* Added *addStripeId* method to user repository and service.
* Updated user migrations.
* Updated payment service.

rg-139: add user stripe

---

frontend/src/bundles/home/pages/templates.tsx
frontend/src/bundles/users/components/delete-account/delete-account.tsx

rg-152: Add placeholder text to search templates

---

backend/src/common/logger/logger.package.ts

Added a new error logger which redirects errors to stderr

rg-162: Add Error Logging To STDERR

---

frontend/src/bundles/preview/preview.tsx

rg-177: - remove duplicate

---

frontend/src/bundles/users/users-api.ts

* Added stub to avoid error on API.

rg-178: * Added stub to fix user delete error.

---

backend/src/bundles/oauth/oauth.service.ts
frontend/src/bundles/auth/store/actions.ts
frontend/src/framework/api/http-api.ts
frontend/src/helpers/helpers.ts
frontend/src/helpers/is-server-error-range.helper.ts

- Added token to storage on sign-up
- Auth error does not throw when it's unnecessary

rg-186: Fix remove auth error, add token

---

frontend/src/bundles/common/hooks/hooks.ts
frontend/src/bundles/landing-page/landing-page.tsx

Added navigation to landing page buttons

rg-200: Landing page BR-19

---

frontend/src/bundles/auth/components/sign-in-form/styles.module.scss
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss

rg-198:  Changed gap according to design file

---

frontend/src/bundles/auth/components/sign-in-form/styles.module.scss
frontend/src/bundles/auth/components/sign-up-form/styles.module.scss

rg-196: Fix link font family variable

---

frontend/src/bundles/resume-access/pages/resume-access.tsx

rg-189: Add a button for unregistered users to sign up on the shared resume page.

---

backend/src/bundles/templates/template.entity.ts
backend/src/bundles/templates/template.model.ts
backend/src/bundles/templates/types/template.type.ts
backend/src/common/database/enums/database-column-name.enum.ts
backend/src/migrations/20240314141509_add_template_name.ts
frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.module.scss
frontend/src/bundles/edit-template/edit-template.tsx
frontend/src/bundles/edit-template/store/actions.ts
frontend/src/bundles/edit-template/store/slice.ts
frontend/src/bundles/home/pages/templates.tsx
shared/src/bundles/templates/types/template-dto.type.ts
shared/src/bundles/templates/types/template-update-item-request-dto.type.ts

rg-222: Add template name

---

frontend/src/bundles/profile/helpers/social-media-profiles.helper.ts

rg-211: Add LinkeIn to social media profiles

---

frontend/src/bundles/edit-template/edit-template.tsx
frontend/src/bundles/edit-template/styles.module.scss

rg-212: * fix BR-20 BR-21

---

frontend/src/assets/css/variables.scss
frontend/src/bundles/home/components/home-top-section/styles.module.scss
frontend/src/bundles/home/pages/styles.module.scss
frontend/src/bundles/home/pages/templates.tsx

rg-207:  Edit Create Template Button Styles

---

backend/src/common/database/enums/database-column-name.enum.ts
backend/src/common/server-application/server-app.ts
frontend/src/bundles/users/components/delete-account/delete-account.tsx
frontend/src/bundles/users/components/delete-account/style.module.scss
frontend/src/framework/store/store.package.ts

**This design was agreed with QA**

rg-201: Update Account Deletion Modal

---

backend/src/migrations/20240313173655_fix_check_constraint_oauth_connections.ts

There was problem to be authenticated via LinkedIn due to constraint on oauth_strategy column in oauth_connection table.
The constraint contained only 3 valid values: github, google, facebook. 
To fix it I created new migration to add linkedin.

rg-210: Migration to fix oauth connections check constraint

---

frontend/src/bundles/users/components/subscription/subscriptions.tsx

rg-224: Changed subscription item titles

---

backend/src/bundles/auth/auth.service.ts

rg-236: Changed user not found error.

---

backend/src/seeds/seed-data/templates-seed.ts
frontend/src/bundles/home/pages/home.tsx

rg-232: Updated template view in homepage.

---

frontend/src/bundles/edit-template/components/template-editor/template-editor.tsx
frontend/src/bundles/edit-template/styles.module.scss

rg-235: Center Template Editor

---

frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.module.scss
frontend/src/bundles/edit-template/edit-template.tsx
frontend/src/bundles/edit-template/styles.module.scss

* Fixed cursor in template editor.
* Fixed name input label.

rg-238: Fix template editor

---

frontend/src/bundles/users/components/profile-form/profile-form.tsx
frontend/src/bundles/users/components/profile-form/style.module.scss

rg-227: Edit Save Button Styles

---

frontend/src/bundles/view-template-page/styles.module.scss
frontend/src/bundles/view-template-page/view-template-page.tsx

rg-231:  Added template name

---

backend/src/bundles/auth/auth.controller.ts
backend/src/common/rate-limit/enums/enums.ts
backend/src/common/rate-limit/enums/reset-password.ts
backend/src/common/rate-limit/enums/retry-settings.ts
backend/src/common/rate-limit/login-registration-rate-limit.ts
backend/src/common/rate-limit/rate-limit.ts
backend/src/common/rate-limit/reset-password.rate-limit.ts
backend/src/common/rate-limit/store/memory-store.ts
backend/src/common/server-application/server-app.ts

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/188  closed
[Trello.add.rate.limit](https://trello.com/c/k5wfznOl/125-log-in-sign-up-rate-limit)
- 2 separate instances of limiter for routes
- Memo store created to be able to reset the attempts for other routes

rg-125: Add rate limiter for login/registration

---

frontend/src/bundles/common/components/user-photo-uploader/styles.module.scss
frontend/src/bundles/common/components/user-photo-uploader/user-photo-preview.tsx

rg-233: New Avatar Section Button Style

---

frontend/src/bundles/common/components/header-wrapper/components/resumes-header/resumes-header.tsx
frontend/src/bundles/common/components/header-wrapper/components/resumes-header/styles.module.scss
frontend/src/bundles/common/components/header-wrapper/constants/constants.ts
frontend/src/bundles/common/components/header-wrapper/constants/resumes-header-routes.ts
frontend/src/bundles/common/components/header-wrapper/header-wrapper.tsx
frontend/src/bundles/resume/pages/resume-page.tsx
frontend/src/bundles/resume/pages/styles.module.scss

rg-253: * move header to ResumesHeader

---

frontend/src/bundles/common/components/header-wrapper/constants/avatar-header-routes.ts
frontend/src/bundles/common/components/header-wrapper/constants/constants.ts
frontend/src/bundles/common/components/header-wrapper/header-wrapper.tsx

rg-270: * change header in /resumes/create route

---

backend/src/bundles/resume-share/resume-share.repository.ts
backend/src/bundles/resume-share/resume-share.service.ts
backend/src/bundles/resumes/resume.service.ts
backend/src/bundles/statistics/statistics.service.ts
frontend/src/bundles/common/components/header-wrapper/constants/get-started-header-routes.ts
frontend/src/bundles/common/components/header-wrapper/header-wrapper.tsx
frontend/src/bundles/resume-access/pages/resume-access.tsx
frontend/src/bundles/resume-access/pages/styles.module.scss
shared/src/bundles/resumes/types/resume-share-response-dto.type.ts
shared/src/bundles/resumes/types/resume.type.ts

rg-286: Resume share refactor

---

frontend/src/bundles/users/components/profile-form/profile-form.tsx
frontend/src/bundles/users/components/profile-form/style.module.scss

rg-249: Change Style of Paragraph

---

backend/src/bundles/resumes/resume.service.ts
frontend/src/bundles/common/components/header-wrapper/header-wrapper.tsx
frontend/src/bundles/common/hooks/use-resumes/use-resumes.hook.ts
frontend/src/bundles/cv-editor/components/container-layout-item/layout-item.tsx
frontend/src/bundles/cv-editor/components/online-editor/online-editor-handler.tsx
frontend/src/bundles/home/components/cards/resume-card/styles.module.scss
frontend/src/bundles/home/components/home-top-section/components/create-resume-button/create-resume-button.tsx
frontend/src/bundles/home/components/home-top-section/components/create-resume-button/styles.module.scss
frontend/src/bundles/home/pages/home.tsx
frontend/src/bundles/resume/helpers/helpers.ts
frontend/src/bundles/resume/helpers/resume-mock/create-resume-from-template-settings.helper.ts
frontend/src/bundles/resume/helpers/resume-mock/update-resume-fields-from-template-settings.helper.ts
frontend/src/bundles/resume/helpers/update-template-settings-avatar.helper.ts
frontend/src/bundles/resume/pages/edit-resume/edit-resume.tsx
frontend/src/bundles/resume/store/actions.ts
frontend/src/bundles/resume/store/slice.ts
frontend/src/bundles/templates-page/store/slice.ts
frontend/src/index.tsx

rg-280: add template selection

---

backend/src/seeds/fill-database.ts
backend/src/seeds/seed-data/resumes-seed.ts

rg-287: Changed resume image seeds

---

frontend/src/bundles/home/components/panel-container/panel-container.tsx

rg-248: Remove Filter Button

---

frontend/src/bundles/home/pages/templates.tsx
frontend/src/bundles/templates-page/store/actions.ts
frontend/src/bundles/templates-page/store/index.ts
frontend/src/bundles/templates-page/store/slice.ts
frontend/src/bundles/templates-page/template-api.ts

Added template delete to templates view page.

rg-279: Add delete templates action.

---

frontend/src/bundles/home/pages/home.tsx
frontend/src/helpers/format-date-to-locale-string.helper.ts
frontend/src/helpers/helpers.ts

rg-298: Add titles dates to resumes templates

---

frontend/src/bundles/statistics-page/pages/statistics-page.tsx

rg-297: * fix display with blank title

---

frontend/src/bundles/edit-template/constants/constants.ts
frontend/src/bundles/edit-template/constants/dropdown-items.constant.ts
frontend/src/bundles/edit-template/edit-template.tsx
frontend/src/bundles/edit-template/enums/enum.ts
frontend/src/bundles/edit-template/enums/enums.ts
frontend/src/bundles/edit-template/enums/font-family.ts
frontend/src/bundles/edit-template/enums/font-size.ts

rg-296: * add dropdowns for text styles

---

frontend/src/bundles/edit-template/styles.module.scss

rg-294: * change color and size of editor icons

---

frontend/src/bundles/common/components/input/input.tsx
frontend/src/bundles/users/components/profile-form/profile-form.tsx

rg-292: Email field disable

---

backend/src/bundles/resumes/interfaces/resume-repository.interface.ts
backend/src/bundles/resumes/interfaces/resume-service.interface.ts
backend/src/bundles/resumes/resume.controller.ts
backend/src/bundles/resumes/resume.repository.ts
backend/src/bundles/resumes/resume.service.ts
frontend/src/bundles/resume/pages/edit-resume/edit-resume.tsx
frontend/src/bundles/resume/store/actions.ts

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/24661681/b2590293-ee6b-414f-86e7-fb0cd33016c5
- Fixed last letter disappear
- Fetch only own resumes
- update resumeTitle

rg-303: Last letter disappear on screenshot

---

frontend/src/bundles/common/components/user-photo-uploader/styles.module.scss

this will not be stretched if img is cropped as non-square

rg-307: Fix stretched image

---

frontend/src/bundles/home/components/home-top-section/components/create-resume-button/create-resume-button.tsx
frontend/src/helpers/get-random-templates.helper.ts
frontend/src/helpers/helpers.ts

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/assets/24661681/7b70f308-232a-470a-a27b-f7b114b63edf

rg-309: Add template selection with one template

---

backend/src/bundles/templates/constants/prettified-template.ts
backend/src/bundles/templates/constants/test-template.ts

Note: run seeds to apply changes

rg-306: Remove default background for university title in templates
